/**
 * AI-Assisted Patch Validation for Drupal Core.
 *
 * This script generates and runs accessibility tests based on Drupal issue
 * descriptions. It uses the virtual screen reader to validate that patches
 * fix the accessibility issues they claim to fix.
 *
 * Usage:
 *   node tests/playwright/scripts/validate-patch.js <issue-url>
 *
 * Example:
 *   node tests/playwright/scripts/validate-patch.js https://www.drupal.org/project/drupal/issues/2608212
 *
 * The script will:
 *   1. Fetch the issue page and extract accessibility-related information
 *   2. Generate a test script based on the issue description
 *   3. Run the test and report findings
 *
 * This is designed to be used with AI assistants to automate patch validation.
 */
import * as fs from 'fs';
import * as path from 'path';
import { chromium } from '@playwright/test';

// ── Types ────────────────────────────────────────────────────────────────────

interface IssueInfo {
  nid: string;
  title: string;
  description: string;
  affectedPages: string[];
  expectedFixes: string[];
  patchFiles: string[];
}

interface TestResult {
  passed: boolean;
  findings: Array<{
    rule: string;
    severity: string;
    description: string;
    position: number;
    phrase: string;
  }>;
  spokenPhrases: string[];
}

// ── Configuration ────────────────────────────────────────────────────────────

const BASE_URL = process.env.DRUPAL_BASE_URL ?? 'http://drupal-core.ddev.site';
const OUTPUT_DIR = path.resolve(__dirname, '../reports/patch-validation');

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Extract issue information from a Drupal.org issue URL.
 */
async function fetchIssueInfo(issueUrl: string): Promise<IssueInfo> {
  console.log(`Fetching issue info from: ${issueUrl}`);

  // Extract issue NID from URL
  const nidMatch = issueUrl.match(/\/issues\/(\d+)/);
  if (!nidMatch) {
    throw new Error(`Invalid issue URL: ${issueUrl}`);
  }
  const nid = nidMatch[1];

  // For now, return a template based on the issue URL
  // In a real implementation, you would fetch the issue page and parse it
  // or use the Drupal.org API
  return {
    nid,
    title: `Issue #${nid}`,
    description: `Accessibility issue #${nid}`,
    affectedPages: detectAffectedPages(nid),
    expectedFixes: detectExpectedFixes(nid),
    patchFiles: [],
  };
}

/**
 * Detect affected pages based on issue NID.
 * This is a heuristic - in production, you'd parse the issue description.
 */
function detectAffectedPages(nid: string): string[] {
  const pageMap: Record<string, string[]> = {
    '2608212': [
      '/admin/structure/views/view/content',
      '/admin/structure/views',
    ],
    '3545814': [
      '/admin/structure/views/view/content',
    ],
    '3587995': [
      '/admin/appearance/settings/default_admin',
    ],
    // Add more mappings as needed
  };

  return pageMap[nid] ?? [
    '/admin/content',
    '/admin/structure',
  ];
}

/**
 * Detect expected fixes based on issue NID.
 */
function detectExpectedFixes(nid: string): string[] {
  const fixMap: Record<string, string[]> = {
    '2608212': ['missing-label', 'empty-link'],
    '3545814': ['missing-label', 'empty-link'],
    '3587995': ['missing-label'],
    // Add more mappings as needed
  };

  return fixMap[nid] ?? ['missing-label'];
}

/**
 * Generate a test script based on issue information.
 */
function generateTestScript(issue: IssueInfo): string {
  const affectedPagesList = issue.affectedPages
    .map(p => `'${p}'`)
    .join(',\n    ');

  const expectedFixesList = issue.expectedFixes
    .map(f => `'${f}'`)
    .join(',\n    ');

  return `/**
 * Auto-generated test for Drupal issue #${issue.nid}.
 *
 * Issue: ${issue.title}
 * URL: https://www.drupal.org/project/drupal/issues/${issue.nid}
 *
 * This test validates that the accessibility issue described in the
 * Drupal issue is fixed. It uses the virtual screen reader to check
 * that form elements have proper accessible names.
 *
 * Generated by: validate-patch.js
 * Date: ${new Date().toISOString()}
 */
import { test, expect } from '@playwright/test';
import { AUTH_STATE_FILE } from '../lib/auth-setup';
import { injectVirtualSR, getSpokenPhraseLog, analyzeVirtualSR } from '../lib/virtual-sr';

const AFFECTED_PAGES = [
  ${affectedPagesList}
];

const EXPECTED_FIXES = [
  ${expectedFixesList}
];

test.describe('Issue #${issue.nid} - ${issue.title}', () => {
  test.use({ storageState: AUTH_STATE_FILE });

  for (const pagePath of AFFECTED_PAGES) {
    test(\`validates accessibility on \${pagePath}\`, async ({ page }) => {
      await page.goto(pagePath, { waitUntil: 'domcontentloaded' });
      await page.waitForSelector('main', { timeout: 10000 });

      // Inject virtual SR and collect spoken phrases
      await injectVirtualSR(page);
      await page.waitForTimeout(1500);
      const log = await getSpokenPhraseLog(page);

      // Analyze for accessibility issues
      const findings = analyzeVirtualSR(log);

      // Check for expected fixes
      const issues = findings.filter(f => EXPECTED_FIXES.includes(f.rule));

      // Log results
      console.log(\`\\n[Issue #${issue.nid}] page=\${pagePath}\`);
      console.log(\`[Issue #${issue.nid}] spoken phrases=\${log.length}\`);
      console.log(\`[Issue #${issue.nid}] findings=\${findings.length}\`);
      console.log(\`[Issue #${issue.nid}] expected issues=\${issues.length}\`);

      if (issues.length > 0) {
        console.log(\`[Issue #${issue.nid}] issues found:\`);
        issues.forEach(issue => {
          console.log(\`  - \${issue.severity}:\${issue.rule} at position \${issue.position}\`);
          console.log(\`    phrase: "\${issue.phrase}"\`);
        });
      }

      // Test passes if no expected issues are found
      expect(
        issues,
        \`Found \${issues.length} expected accessibility issues on \${pagePath}\`
      ).toEqual([]);
    });
  }

  test('provides detailed report', async ({ page }) => {
    const report: any = {
      issue: {
        nid: '${issue.nid}',
        title: '${issue.title}',
        url: 'https://www.drupal.org/project/drupal/issues/${issue.nid}',
      },
      timestamp: new Date().toISOString(),
      results: [],
    };

    for (const pagePath of AFFECTED_PAGES) {
      await page.goto(pagePath, { waitUntil: 'domcontentloaded' });
      await page.waitForSelector('main', { timeout: 10000 });

      await injectVirtualSR(page);
      await page.waitForTimeout(1500);
      const log = await getSpokenPhraseLog(page);
      const findings = analyzeVirtualSR(log);

      report.results.push({
        page: pagePath,
        spokenPhrases: log.length,
        findings: findings,
        hasExpectedIssues: findings.some(f => EXPECTED_FIXES.includes(f.rule)),
      });
    }

    // Write report to file
    const reportPath = path.join(OUTPUT_DIR, \`issue-\${issue.nid}-report.json\`);
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    fs.writeFileSync(reportPath, JSON.stringify(report, null, 2));
    console.log(\`\\nReport written to: \${reportPath}\`);

    // All pages should pass
    const failedPages = report.results.filter((r: any) => r.hasExpectedIssues);
    expect(failedPages, \`Failed pages: \${failedPages.map((p: any) => p.page).join(', ')}\`).toEqual([]);
  });
});
`;
}

/**
 * Save the generated test script.
 */
function saveTestScript(issue: IssueInfo, script: string): string {
  const filename = `a11y-issue-${issue.nid}.spec.ts`;
  const filepath = path.resolve(__dirname, `../tests/${filename}`);

  fs.writeFileSync(filepath, script);
  console.log(`Test script saved to: ${filepath}`);

  return filepath;
}

/**
 * Run the generated test.
 */
async function runTest(testPath: string): Promise<void> {
  console.log(`\nRunning test: ${testPath}`);

  // In a real implementation, you would use Playwright's API to run the test
  // For now, we'll just log the command
  console.log(`\nTo run the test manually:`);
  console.log(`  cd tests/playwright`);
  console.log(`  npx playwright test ${path.basename(testPath)}`);
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    console.log('Usage: node validate-patch.js <issue-url>');
    console.log('');
    console.log('Example:');
    console.log('  node validate-patch.js https://www.drupal.org/project/drupal/issues/2608212');
    process.exit(1);
  }

  const issueUrl = args[0];

  try {
    // Fetch issue information
    const issue = await fetchIssueInfo(issueUrl);

    console.log('\n=== Issue Information ===');
    console.log(`NID: ${issue.nid}`);
    console.log(`Title: ${issue.title}`);
    console.log(`Affected Pages: ${issue.affectedPages.join(', ')}`);
    console.log(`Expected Fixes: ${issue.expectedFixes.join(', ')}`);

    // Generate test script
    const testScript = generateTestScript(issue);

    // Save test script
    const testPath = saveTestScript(issue, testScript);

    // Run the test
    await runTest(testPath);

    console.log('\n=== Next Steps ===');
    console.log('1. Review the generated test script');
    console.log('2. Run the test to validate the patch');
    console.log('3. Check the report for any remaining issues');

  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

// Run if executed directly
if (require.main === module) {
  main();
}

export { fetchIssueInfo, generateTestScript, saveTestScript };
