// Builds cloud/, the static site for GitHub Pages, from the same sources the local viewer uses (no second copy to maintain):
//   cloud/index.html    tools/compare/index.html unchanged (it detects that it is static and hides what needs the server)
//   cloud/variants.json the variants, minus anything machine-specific, plus the repository URL
//   cloud/images/       a few screenshots from docs/images
// Usage: node scripts/build-cloud.mjs [--check]     (--check fails if cloud/ is out of date; used by CI)
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { labRoot, variants } from '../tools/compare/lib.mjs';

const check = process.argv.includes('--check');
const out = path.join(labRoot, 'cloud');
const remote = execFileSync('git', ['-C', labRoot, 'remote', 'get-url', 'origin'], { encoding: 'utf8' }).trim();
const repo = remote.replace(/^git@github\.com:/, 'https://github.com/').replace(/\.git$/, '');
const pick = (v) => ({ slug: v.slug, issue: v.issue, label: v.label, description: v.description, steps: v.steps, expected: v.expected, actual: v.actual, setup: v.setup, observe: v.observe, checks: v.checks, pages: v.pages, demo: v.demo });
const files = {
  'index.html': fs.readFileSync(path.join(labRoot, 'tools/compare/index.html'), 'utf8').replace('__BUILD__', 'static'),
  'variants.json': JSON.stringify({ static: true, repo, variants: variants().map(pick) }, null, 2) + '\n',
  '.nojekyll': '',
  'README.md': 'GENERATED by `node scripts/build-cloud.mjs`. Do not edit here: change `tools/compare/index.html` or `tools/compare/variants.json` and rebuild.\nPublished by `.github/workflows/pages.yml`.\n',
};
const images = ['viewer-frames.png', 'viewer-overview.png'];
let stale = [];
const write = (rel, data) => {
  const f = path.join(out, rel);
  const same = fs.existsSync(f) && Buffer.compare(fs.readFileSync(f), Buffer.from(data)) === 0;
  if (!same) { stale.push(rel); if (!check) { fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, data); } }
};
for (const [rel, data] of Object.entries(files)) write(rel, data);
for (const i of images) write(`images/${i}`, fs.readFileSync(path.join(labRoot, 'docs/images', i)));
if (check && stale.length) { console.error(`cloud/ is out of date (${stale.join(', ')}). Run: node scripts/build-cloud.mjs`); process.exit(1); }
console.log(check ? 'cloud/ is up to date.' : stale.length ? `Updated cloud/: ${stale.join(', ')}` : 'cloud/ already up to date.');
