// Regenerate reports/issues/README.md from what is actually in each issue folder.
//   node scripts/index-issues.mjs
import fs from 'node:fs';
import path from 'node:path';
import { labRoot, variants } from '../tools/compare/lib.mjs';

const root = path.join(labRoot, 'reports/issues');
const vs = variants();
const walk = (d) => (fs.existsSync(d) ? fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)])) : []);
const rows = [];
for (const nid of fs.readdirSync(root).filter((n) => /^\d+$/.test(n)).sort()) {
  const dir = path.join(root, nid); const files = walk(dir).map((f) => path.relative(dir, f));
  const heading = (f) => { if (!f) return ''; const p = path.join(dir, f); if (!fs.existsSync(p) || !fs.statSync(p).isFile()) return ''; const m = fs.readFileSync(p, 'utf8').match(/^#\s+(.*)$/m); return m ? m[1].replace(/^Reproduce #\d+:\s*/, '').slice(0, 80) : ''; };
  const title = heading('REPRODUCE.md') || heading(files.find((f) => /^(ISSUE-|STATUS|.*-update|.*\.md$)/.test(f)) || '') || '(see folder)';
  const patches = files.filter((f) => f.endsWith('.patch')).length;
  const status = files.filter((f) => /^STATUS-/.test(f)).sort().pop();
  const evidence = files.filter((f) => /^(playwright|screenreader|compare)\/[^/]+\/SUMMARY\.md$/.test(f) || /^playwright\/[^/]+\/SUMMARY\.md$/.test(f)).length;
  const my = vs.filter((x) => String(x.issue) === nid).map((x) => '`' + x.slug + '`').join(', ');
  rows.push(`| [${nid}](${nid}/) | ${title} | ${files.includes('REPRODUCE.md') ? '[yes](' + nid + '/REPRODUCE.md)' : 'no'} | ${patches} | ${status ? status.replace('STATUS-', '').replace('.md', '') : ''} | ${evidence || ''} | ${my || ''} |`);
}
const md = `# Issues evaluated in this lab

Generated by \`node scripts/index-issues.mjs\`; do not edit by hand. Statuses on drupal.org change: the "Status snapshot"
column is the date of the newest dated note, not a live status. Re-check an issue on drupal.org before relying on it.

To come back to an issue: open its \`REPRODUCE.md\` (where present) and run the commands for its pinned variant. To start a new
one: \`node scripts/new-issue.mjs <nid> --branch <fork-branch>\` (see \`docs/NEW-ISSUE.md\`).

| Issue | What | Reproduction guide | Patches | Status snapshot | Evidence runs | Variants |
|---|---|---|---|---|---|---|
${rows.join('\n')}
`;
fs.writeFileSync(path.join(root, 'README.md'), md);
console.log(`${rows.length} issues indexed -> reports/issues/README.md`);
